from __future__ import annotations


SAMPLE_PROFESSORS: list[dict[str, object]] = [
    {
        "name": "张三教授",
        "email": "zhangsan@tsinghua.edu.cn",
        "title": "教授/博导",
        "university": "清华大学",
        "school": "计算机科学与技术系",
        "department": "智能技术实验室",
        "research_direction": "自然语言处理，大语言模型，AI Agent",
        "recent_papers": ["Agent Planning", "LLM for Research Assistance"],
        "profile_url": "https://example.edu/professors/zhangsan",
        "source_url": "https://example.edu/faculty",
    },
    {
        "name": "李四研究员",
        "email": "lisi@pku.edu.cn",
        "title": "特聘研究员",
        "university": "北京大学",
        "school": "智能学院",
        "department": "视觉智能组",
        "research_direction": "计算机视觉，目标检测，多模态学习",
        "recent_papers": ["Vision-Language Grounding", "Multi-modal Reasoning"],
        "profile_url": "https://example.edu/professors/lisi",
        "source_url": "https://example.edu/faculty",
    },
    {
        "name": "王五副教授",
        "email": "wangwu@zju.edu.cn",
        "title": "副教授/硕导",
        "university": "浙江大学",
        "school": "软件学院",
        "department": "Web 系统实验室",
        "research_direction": "全栈开发，Web 系统架构，微服务",
        "recent_papers": ["Modern Web Architecture", "Service Reliability"],
        "profile_url": "https://example.edu/professors/wangwu",
        "source_url": "https://example.edu/faculty",
    },
    {
        "name": "赵六教授",
        "email": "zhaoliu@sjtu.edu.cn",
        "title": "教授/博导",
        "university": "上海交通大学",
        "school": "电子信息与电气工程学院",
        "department": "机器人实验室",
        "research_direction": "强化学习，具身智能，机器人控制",
        "recent_papers": ["Embodied RL", "Control under Uncertainty"],
        "profile_url": "https://example.edu/professors/zhaoliu",
        "source_url": "https://example.edu/faculty",
    },
    {
        "name": "孙七导师",
        "email": "sunqi@fudan.edu.cn",
        "title": "助理教授",
        "university": "复旦大学",
        "school": "计算机科学技术学院",
        "department": "数据智能组",
        "research_direction": "数据挖掘，推荐系统，图神经网络",
        "recent_papers": ["Graph Recommender Systems", "Mining Academic Graphs"],
        "profile_url": "https://example.edu/professors/sunqi",
        "source_url": "https://example.edu/faculty",
    },
]
