"""create core tables

Revision ID: 04d66ff4c25b
Revises: 
Create Date: 2026-04-18 12:51:16.812097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d66ff4c25b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), server_default=sa.text('(465)'), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_username', sa.String(length=255), nullable=True),
    sa.Column('imap_password', sa.String(length=255), nullable=True),
    sa.Column('default_language', sa.String(length=32), server_default=sa.text("'zh-CN'"), nullable=False),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('match_threshold', sa.Integer(), nullable=True),
    sa.Column('daily_send_limit', sa.Integer(), nullable=True),
    sa.Column('send_interval_min', sa.Integer(), nullable=True),
    sa.Column('send_interval_max', sa.Integer(), nullable=True),
    sa.Column('same_domain_cooldown_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_profiles')),
    sa.UniqueConstraint('email_address', name=op.f('uq_identity_profiles_email_address'))
    )
    op.create_table('llm_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('matcher_prompt_template', sa.Text(), nullable=True),
    sa.Column('writer_prompt_template', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_llm_profiles_name'))
    )
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('research_direction', sa.Text(), nullable=True),
    sa.Column('recent_papers', sa.JSON(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('crawl_status', sa.String(length=64), server_default=sa.text("'discovered'"), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professors')),
    sa.UniqueConstraint('email', name=op.f('uq_professors_email'))
    )
    op.create_table('attachment_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity_profiles.id'], name=op.f('fk_attachment_assets_identity_id_identity_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment_assets'))
    )
    op.create_index(op.f('ix_attachment_assets_identity_id'), 'attachment_assets', ['identity_id'], unique=False)
    op.create_table('email_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('llm_profile_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'discovered'"), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('generated_subject', sa.Text(), nullable=True),
    sa.Column('generated_content_text', sa.Text(), nullable=True),
    sa.Column('generated_content_html', sa.Text(), nullable=True),
    sa.Column('selected_attachments', sa.JSON(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_replied', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity_profiles.id'], name=op.f('fk_email_tasks_identity_id_identity_profiles')),
    sa.ForeignKeyConstraint(['llm_profile_id'], ['llm_profiles.id'], name=op.f('fk_email_tasks_llm_profile_id_llm_profiles')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_email_tasks_professor_id_professors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tasks'))
    )
    op.create_index(op.f('ix_email_tasks_identity_id'), 'email_tasks', ['identity_id'], unique=False)
    op.create_index(op.f('ix_email_tasks_llm_profile_id'), 'email_tasks', ['llm_profile_id'], unique=False)
    op.create_index(op.f('ix_email_tasks_professor_id'), 'email_tasks', ['professor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_tasks_professor_id'), table_name='email_tasks')
    op.drop_index(op.f('ix_email_tasks_llm_profile_id'), table_name='email_tasks')
    op.drop_index(op.f('ix_email_tasks_identity_id'), table_name='email_tasks')
    op.drop_table('email_tasks')
    op.drop_index(op.f('ix_attachment_assets_identity_id'), table_name='attachment_assets')
    op.drop_table('attachment_assets')
    op.drop_table('professors')
    op.drop_table('llm_profiles')
    op.drop_table('identity_profiles')
    # ### end Alembic commands ###
